### ISSUE TITLE
Enable JPEG Support

### ISSUE THREAD

**Issue by janhelke** [wmdbsystems/WMDB.BudgetPlan#30]
When I upload a picture of a receipt I took with with my mobile, I got an error message:

500 Internal Server Error
An internal error occurred.
When contacting the maintainer of this application please mention the following reference code:
2015051106261835dde3

I think, the issue is more about JPEG in general than "image taken with my mobile" because the error also occurs when I generate an JPEG with Photoshop.

At least the system should return a clear error message like "Sorry, JPEG files are not allowed". Better would it be, it JPEG files woul work.

**Comment by wmdbMattes** [comment]
umm, yes... Indeed it only handles PNG and PDF.
Andy, can you check why the Exception in ReimbursementController.php Line 410 isn't written to disk?
