### ISSUE TITLE
Profile Update throws error without further infos

### ISSUE THREAD

**Issue by maddy2101** [wmdbsystems/WMDB.BudgetPlan#47]
I just followed the friendly invitation to update the profile, filled in all fields and was regarded with
An error occurred while trying to call WMDB\BudgetPlan\Controller\ProfileController->updateAction()
No further information is given.

**Comment by maddy2101** [comment]
Addition: I tried to deny the Paypal Email by inserting a dash. That satisfied the JavaScript Validation, but causer server side to refuse. Any comment would be nice, though. After inserting a valid email (which is a fake one) the saveAction was successfully called.

**Comment by andreasfernandez** [comment]
Do you remember whether you got an error code?

**Comment by maddy2101** [comment]
no, can't remember. But I think this ticket is solved with the rework of bank data?

**Comment by andreasfernandez** [comment]
Alright, I will close this now. When the issue occurs again, feel free to make some noise ;)
